### PR TITLE
Improve right prompt

### LINKED ISSUE #9: print and format $CMD_DURATION in right prompt
it would be nice to have the `$CMD_EXECUTION` info in the right prompt. see #8

### PR DESCRIPTION
**Pull request by phra**
i made some small improvements to the right prompt of lambda theme and i would like to merge them to the main repository.

1. print green exit status if `0`
2. print and format `$CMD_DURATION`

image

fixes #9

### CODE REVIEW

**Comment by phra** [comment]
@hasanozgan any update?

**Comment by js402882** [comment]
I have visually more subtle and much simpler implementation for **$CMD_DURATION** display (basically no more than 1 one-liner). If there would be response and interest from @hasanozgan I can prepare merge request for it.

image

**Comment by phra** [comment]
@js402882 i can give you access to my fork to update this PR if you want.

**Comment by phra** [comment]
@hasanozgan @js402882 is anyone alive guys?

**Comment by faogustavo** [comment]
@phra @hasanozgan I'm facing some problems with these changes.
After taking a look at the code I discovered that the problem is in the line 16.
The math done in this line, shows me an error message like this:

`0.000001: value not completely converted`

After commenting this line, everything works properly.

image

My setup is:
- OS: Linux (Debian 10 - but had the same problem on ubuntu 19.04 and 19.10)
- KDE IDE
- Using [Hyper](http://hyper.is/) or [Konsole](https://konsole.kde.org/)

**Comment by alonsodomin** [comment]
Same happens in MacOS, there is a fix in #12.

To be honest, this should have never been merged, there is little value in the additional `$CMD_DURATION` info in the prompt and because of poor testing, it broke a perfectly working prompt.

**Pull request merged**
